name: Slack Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_USER_ID: ${{ secrets.SLACK_USER_ID }}
      JOBCON_URL: ${{ secrets.JOBCON_URL }}
      JOBCON_ID: ${{ secrets.JOBCON_ID }}
      JOBCON_PASSWORD: ${{ secrets.JOBCON_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          mv ngrok /usr/local/bin/ngrok

      - name: Start Ngrok
        run: nohup ngrok http 3000 &

      - name: Wait for Ngrok to start
        run: sleep 10

      - name: Extract Ngrok URL
        id: extract_ngrok
        run: echo "::set-output name=ngrok_url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

      - name: Run Python script
        run: python3 slack_timeclock_auto.py
        env:
          NGROK_URL: ${{ steps.extract_ngrok.outputs.ngrok_url }}

